server:
  port: 8085

spring:
  application:
    name: 05-redis-listener

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
