server:
  port: 8081

spring:
  application:
    name: 01-lazy-jdbc-connection-fetching

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
    # Spring Boot 4.1 supports connection-fetch: lazy natively
    # In older versions, we can use a custom LazyDataSourceConfig
    connection-fetch: eagle #lazy, eagle
    hikari:
      maximum-pool-size: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
